### ISSUE TITLE
Support Bootstrap 5

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#1494]
Trying to summarize what the minimum changes are to support Bootstrap 5.

- [x] Support v5 in the addon's index.js. PR: #1496 
- [x] Add support for `--bootstrap-version=5` in the default blueprint (with v4 still being the default for now) PR: #1497
- [x] Update [setup docs](https://www.ember-bootstrap.com/getting-started/setup) #1617 
- [x] Setup CI for BS5. PR: #1499 
- [x] Deprecate BS3. Only loosely related to BS5 support, but I think we don't want to support all three versions for an extended time. But to introduce BS5 support without a major bump, we might have to do it for some time. As there are not many renamed classes, this seems doable. PR: #1536 
- [x] Update markup for Accordion, see https://getbootstrap.com/docs/5.0/components/accordion/ PR: #1561 
- [x] Update markup for Forms, see https://getbootstrap.com/docs/5.0/migration/#forms. PR: #1512
- [x] Update markup for Buttons, see https://getbootstrap.com/docs/5.0/migration/#buttons PR: #1537 
- [x] Update toggle buttons for ButtonGroups, see https://getbootstrap.com/docs/5.0/migration/#buttons PR: #1540 
- [x] Update markup for Navbars, see https://getbootstrap.com/docs/5.0/migration/#navbars PR: #1597
- [x] Update markup for Popovers, see https://getbootstrap.com/docs/5.0/migration/#popovers. PR: #1502
- [x] Update markup for Tooltips, see https://getbootstrap.com/docs/5.0/migration/#tooltips. PR: #1502
- [x] BS4 uses popper.js v2. Do we have to follow here? `ember-popper` hasn't been maintained much, https://github.com/alexlafroscia/ember-popper-modifier seems like a more modern and up to date solution, and uses v2.
- [x] BS5 drops support for IE11 :tada:. While this doesn't really affect us technically, it at least makes dropping support in our addon even more desirable. ~Probably~ in *our* v5, ~maybe including requiring Ember 4.0 as the minimum version then?~ #1596 
- [x] Change use of `.sr-only` to `.visually-hidden`
- [x] Fix modal close button, see [this comment](https://github.com/kaliber5/ember-bootstrap/issues/1494#issuecomment-917175019) #1614 

Any kind of contributions (PRs, documentation, testing) highly welcome! Just comment here if you are interested in helping out!

/cc @jelhan

**Comment by vlascik** [comment]
Also, modal dialog's close button changed the class from `close` to `btn-close`.

I have a script with more of the changes to bootstrap classes listed at https://github.com/vlascik/bootstrap4-to-5-migrator , might be of some use to you.

**Comment by simonihmig** [comment]
Thanks @vlascik, I'll look into it! Or do you have time for a PR? 😀

**Comment by simonihmig** [comment]
> Also, modal dialog's close button changed the class from close to btn-close.

https://github.com/kaliber5/ember-bootstrap/pull/1614 should fix this.

**Comment by simonihmig** [comment]
Seems we are done here! 🎉 

Wondering if we should make BS5 the default for our upcoming v5? 🤔

Changing the default is not really a breaking change I think, as the version is "pinned" in `ember-cli-build.js`, but the new major seems a good moment to do the switch nevertheless!? @jelhan thoughts?

**Comment by vst** [comment]
> Changing the default is not really a breaking change I think, as the version is "pinned" in `ember-cli-build.js`, but the new major seems a good moment to do the switch nevertheless!? @jelhan thoughts?

I agree.

**Comment by jelhan** [comment]
> Changing the default is not really a breaking change I think, as the version is "pinned" in `ember-cli-build.js`, but the new major seems a good moment to do the switch nevertheless!? @jelhan thoughts?

Fully agree. Let's switch to Bootstrap 5. :+1:

**Comment by vst** [comment]
Quick feedback, FWIW: I have been using v5.0.0-beta.0 on BS5 for the last few days. I did not notice any regressions or errors so far, at least not due to `ember-bootstrap`.

**Comment by simonihmig** [comment]
Thanks @vst for the feedback! There was one issue related to alerts though, which was fixed in #1620, but this is yet to be released! fyi

**Comment by simonihmig** [comment]
BTW, I started working migrating the docs app (ember-bootstrap.com) to BS5, and noticed some missing margins for forms. So some minor issues still need to be sorted out...

**Comment by vst** [comment]
@simonihmig Got it, thanks! Will report anything we bump into.
