### ISSUE TITLE
Remove usage of action template helper and modifier

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#2131]
The `(action)` template helper and `{{action}}` modifier has been deprecated. See [RFC 1006](https://rfcs.emberjs.com/id/1006-deprecate-action-template-helper/) for details.

We are still relying on both at many places. In the addon itself, in the test app, and in the documentation app. We should refactor away from it especially in the addon code shipped to consumers as soon as possible.

These are the files where the action helper is still used:
- [x] `test-app/tests/integration/components/bs-accordion/item-test.js` #2150
- [x] `test-app/tests/integration/components/bs-alert-test.js` #2150
- [x] `test-app/tests/integration/components/bs-dropdown-test.js` #2146
- [x] `test-app/tests/integration/components/bs-dropdown/toggle-test.js` #2146
- [x] `test-app/tests/integration/components/bs-form-test.js` #2148
- [x] `test-app/tests/integration/components/bs-form/element-test.js` #2148
- [x] `test-app/tests/integration/components/bs-modal-simple-test.js` #2147
- [x] `test-app/tests/integration/components/bs-modal-test.js` #2147
- [x] `test-app/tests/integration/components/bs-nav/item-test.js` #2149
- [x] `test-app/tests/integration/components/bs-navbar-test.js` #2149
- [x] `test-app/tests/integration/components/bs-popover-test.js` #2150
- [x] `test-app/tests/integration/components/bs-tab-test.js` #2150
- [x] `test-app/tests/integration/components/bs-tooltip-test.js` #2150

The JSDoc comments also still use the action helper the following places:
- [x] `ember-bootstrap\addon\components\bs-tooltip.js` #2152
- [x] `ember-bootstrap\addon\components\bs-tab.js` #2152
- [x] `ember-bootstrap\addon\components\bs-popover.js` #2152
- [x] `ember-bootstrap\addon\components\bs-navbar.js` #2152
- [x] `ember-bootstrap\addon\components\bs-modal.js` #2152
- [x] `ember-bootstrap\addon\components\bs-form.js` #2152
- [x] `ember-bootstrap\addon\components\bs-dropdown.js` #2152
- [x] `ember-bootstrap\addon\components\bs-form\element.js` #2152
- [x] `ember-bootstrap\addon\components\bs-button-group.js` #2152
- [x] `ember-bootstrap\addon\components\bs-button.ts` #2163 

After that, the configuration should be updated to re-enable the warning:
- [x] update `test-app/.templatelintrc.js` #2151

**Comment by simonihmig** [comment]
> In the addon itself

I have only found these in example code in JSDocs comments. Definitely not what we want, but not nearly as bad as in our own code... or did I miss some places?

**Comment by jelhan** [comment]
> > In the addon itself
> 
> I have only found these in example code in JSDocs comments. Definitely not what we want, but not nearly as bad as in our own code... or did I miss some places?

You are right. I only looked which files includes `{{action`. But not on the actual context within the file. It seems to affect API docs only.

**Comment by SanderKnauff** [comment]
@jelhan I think I forgot to update this issue after the PRs got merged. Do you think this can be closed?

**Comment by jelhan** [comment]
> @jelhan I think I forgot to update this issue after the PRs got merged. Do you think this can be closed?

I searched for `{{action` and `(action` in the repository. I think we missed two cases in the API docs:

* https://github.com/ember-bootstrap/ember-bootstrap/blob/3b085e74e3369360e8d0e23a8acfcec429564cd1/ember-bootstrap/addon/components/bs-button.ts#L76
* https://github.com/ember-bootstrap/ember-bootstrap/blob/3b085e74e3369360e8d0e23a8acfcec429564cd1/ember-bootstrap/addon/components/bs-button.ts#L132

Beside those two everything looks good.

I fear I missed searching for `(action` when creating the list above.

**Comment by SanderKnauff** [comment]
> > @jelhan I think I forgot to update this issue after the PRs got merged. Do you think this can be closed?
> 
> I searched for `{{action` and `(action` in the repository. I think we missed two cases in the API docs:
> 
>     * https://github.com/ember-bootstrap/ember-bootstrap/blob/3b085e74e3369360e8d0e23a8acfcec429564cd1/ember-bootstrap/addon/components/bs-button.ts#L76
> 
>     * https://github.com/ember-bootstrap/ember-bootstrap/blob/3b085e74e3369360e8d0e23a8acfcec429564cd1/ember-bootstrap/addon/components/bs-button.ts#L132
> 
> 
> Beside those two everything looks good.
> 
> I fear I missed searching for `(action` when creating the list above.

Aha! I've created https://github.com/ember-bootstrap/ember-bootstrap/pull/2163 to remove them as well. Those indeed seem to be the only left over.
