### ISSUE TITLE
Improve support for handling interim states on buttons and forms

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#638]
`{{bs-button}}`, `{{bs-form}}` and `{{bs-modal-simple}}` are all dealing with interim states (pending actions). Currently support for them is quite limited. `{{bs-button}}` allows to change the button label depending on promises state. But that's all. The others does not help with showing interim states at all.

This issue should outline the bigger picture and track the work needed. Implementation has already been started. If possible, it should be accomplished without any breaking change to not have to wait for next major release.

# Common use cases

Many application shares the same logic for visual feedback about state of action (*pending*, *fulfilled*, *rejected*). Ember-bootstrap can't support all of them out of the box, but it should be as easy as possible to implement the application specific logic by overriding at little overrides as possible.

## Button

* Button should have another label while action is pending, fulfilled or rejected.
* Button should show a loading spinner while action is pending.
* Button should be disabled while action is pending.
* Button should have another type if action is fulfilled (`btn-success`) or rejected (`btn-danger`).
* Button should not fire another action if one is pending (like using an `ember-concurrency` task with `drop()` modifier).

## Form

* Submit button should have another label if action is pending, fulfilled or rejected.
* Submit button should show a loading spinner while action is pending.
* Submit button should be disabled while action is pending.
* Submit button should have another type if form has been submitted successfully (`btn-success`) or submission has failed (`btn-danger`). It should be reset automatically if form values are changed.
* Rollback button should be disabled while action is pending.
* Form should not submit if another submission is pending (like using an `ember-concurrency` task with `drop()` modifier).

## bs-modal-simple

Modal buttons should reflect submission states as normal form buttons would do if a form is used inside a `{{bs-form-simple}}`.

# Usage example

All mentioned use cases should be supported by overriding `{{bs-button}}` in application *only*. An example might look like:

```
// app/components/bs-button.js

import BsButton from 'ember-bootstrap/components/bs-button';
import { computed } from '@ember/object';
import { reads } from '@ember/object/computed';

export default BsButton.extend({
  disabled: reads('isPending'),
  type: computed('state', function() {
    switch (this.get('state')) {
      case 'fulfilled':
        return 'success';

      case 'rejected':
        return 'danger';

      default:
        return 'default';
    }
  })
});
```

```
// app/templates/components/bs-button.hbs

{{yield}}
{{#if isPending}}
  {{fa-icon "spinner" spin=true}}
{{/if}}
```

# Tasks

* [x] `{{bs-button}}` yields state of action (`isPending`, `isRejected`, `isFulfilled`, `isSettled`). (#625)
* [x] `{{bs-form}}` yields `isSubmitting` state. (#627)
* [ ] `{{bs-form}}` yields `isSubmitted` and `isRejected` properties that reflects submission results and gets reset as soon as any value of form changes.
* [ ] `{{bs-form}}` yields a `{{form.button}}` component that binds form submitting state to button state.
* [ ] `{{bs-modal-simple}}` yields a `{{modal.form}}` component, which binds submission of that forms to `onSubmit` event of modal and binds submission state to submit button of modal.
* [ ] `{{bs-button}}` could be configured to not fire `onClick` event if a promise returned by an early click event is still pending.
* [ ] `{{bs-form}}` could be configured to not fire `onSubmit` event if a promise returned by an early submit event is still pending.

**Comment by Techn1x** [comment]
Sounds good to me. Covers the use cases I can think of..

Is this sort of what we're aiming for for usage?

```handlebars
// Button on its own
{{#bs-button onClick=(action "submitAction") as |button|}}
  {{#if button.isFulfilled}}
    {{fa-icon 'check'}} Sent
  {{else if button.isPending}}
    {{fa-icon 'spinner'}} Submitting
  {{else if button.isRejected}}
    {{fa-icon 'times'}} Failed
  {{else}}
    {{fa-icon 'floppy-o'}} Submit
  {{/if}}
{{/bs-button}}

// Button in a form
{{#bs-form ... onSubmit=(action "submitAction") as |form|}}
  {{#form.button as |formBtn|}}
    {{#if formBtn.isFulfilled}}
      ...
    {{/if}}
  {{/form.button}}
{{/bs-form}}
```

```javascript
actions:{
  submitAction() {
    return this.get('saveTask').perform(); // some kind of promise eg ember-concurrency task
  }
}
```

**Comment by jelhan** [comment]
> Is this sort of what we're aiming for for usage?

Exactly. But I expect the indication of interim states mostly to be handled by an override of `{{bs-button}}` template. Cause that would allow a consistent look and feel throughout the application by just using a `{{bs-button}}` or a component extended from it (e.g. `{{form.button}}`).

It would also provide some of the functionality which usually is provided by ember-concurrency. You wouldn't have to use an ember-concurrency task with `drop` modifier anymore to make sure that the action is not fired concurrently.

**Comment by svparijs** [comment]
@jelhan how far along is this MR?

**Comment by jelhan** [comment]
@svparijs All basic APIs have landed. Only missing higher level integration between button and form states (`form` yielding a `button` component) and with `bs-modal-simple`. Please have a look at task list in first post for details. All checked items are available in latest release.

**Comment by jelhan** [comment]
We should rethink recommended usage of `<BsForm>` within a `<BsModal>`. I'm not convinced that `<BsModal>` should yield a `<BsForm>`. At least we should investigate before if Embroider would be still able to only pull in `<BsModal>` if yielded `<BsForm>` component is not used.
