### ISSUE TITLE
Road to v4

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#957]
### Breaking Changes:

- [x] Drop support for Ember < 3.15 (aka Octane) for RC releases / 3.16 (LTS) for stable release [#965] 

- [x] Drop node 8 support [#965] 

- [x] Refactor all components to tag-less/outerHTML components (only breaking in rare cases, e.g. using `ember-test-selectors` with curly invocation syntax)
  - [x] Accordion #1001 
  - [x] Alert #976
  - [x] Button #980 
  - [x] Button Group #985
  - [x] Carousel #1002 
  - [x] Collapse #996 
  - [x] Dropdown #980 
  - [x] Form #1005
  - [x] Modal #981 
  - [x] Navbar #997 
  - [x] Nav #988 
  - [x] ~Popover~
  - [x] Progress #982 
  - [x] Tabs #998 
  - [x] ~Tooltip~

- [x] Drop all arguments for HTML attributes (#826) and add warnings if they are still used

### Other

- [x] Refactor tests to angle brackets [#966] 
- [x] Use new build helpers (#984), remove separate `bs3`/`bs4` trees #1006 
- [x] Implement AST transforms for build helpers - at build time, with proper branch elimination 

### Release blockers

On the way we noticed some potential release blockers related to deprecation of arguments:

- [ ] Ember does not support `type` HTML attribute for `...attributes` if already set on the element: https://github.com/emberjs/ember.js/issues/18232 This breaks `<BsButton type="submit" />`.
- [ ] Ember Power Select does not support replacing some arguments by HTML attributes yet. This breaks `ember-bootstrap-power-select`: https://github.com/kaliber5/ember-bootstrap-power-select/issues/93

### Outlook

This allows refactoring all components step by step to Glimmer components during v4.x releases. This will cause breaking changes for consumers extending Ember Bootstrap classes. We don't consider extending the components as part of our public API but will not do such changes in patch releases.

**Comment by simonihmig** [comment]
I started to work on https://github.com/ember-codemods/tagless-ember-components-codemod/issues/3, let's see how this turns out. Hopefully this will allow us to do the tag-less refactoring without much further effort on this side!

**Comment by jelhan** [comment]
> Drop all (deprecated) properties for HTML attributes (#826)

We can't add deprecations for all arguments used for HTML attributes. Some of them are used internally and `component` helper does not support passing HTML attributes yet. In some cases (e.g. `buttonType` argument of `<BsButton>` we decided to create a separate argument only used for internals. But for other cases - especially control types of forms - that would mean adding a lot of additional arguments just for deprecation purposes. We decided not to do this cause we fear that this might have a bad impact on performance.

We are currently discussing how we can help consumers with migration even if we can't add a deprecation. We might add a warning after removing them to highlight invocations that need to be updated.

**Comment by jelhan** [comment]
On the way we noticed some potential release blockers related to deprecation of arguments:

- [ ] Ember does not support `type` HTML attribute for `...attributes` if already set on the element: https://github.com/emberjs/ember.js/issues/18232 This breaks `<BsButton type="submit" />`.
- [ ] Ember Power Select does not support replacing some arguments by HTML attributes yet. This breaks `ember-bootstrap-power-select`: https://github.com/kaliber5/ember-bootstrap-power-select/issues/93

**Comment by jelhan** [comment]
We should consider providing a codemod for arguments to attributes transform. Fear it would be a lot of mechanical work if done manual.

**Comment by simonihmig** [comment]
> Drop all arguments for HTML attributes (#826) and add warnings if they are still used

@jelhan as you worked on this, this is basically done, isn't it? (except for the still pending `button#type` issue)

**Comment by jelhan** [comment]
> @jelhan as you worked on this, this is basically done, isn't it? (except for the still pending `button#type` issue)

I think we should double-check that we didn't missed an argument that we want to deprecate. I'm also not sure if we have warnings for all of them. But we can also do as part of a first release candidate.
